version: '3.8'

services:
  # 应用服务 - 前后端一体化
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - DATABASE_URL=${DATABASE_URL}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - JWT_ADMIN_SECRET=${JWT_ADMIN_SECRET}
        - JWT_APP_SECRET=${JWT_APP_SECRET}
    container_name: cursor-reset-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - GIN_MODE=release
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_ADMIN_SECRET=${JWT_ADMIN_SECRET}
      - JWT_APP_SECRET=${JWT_APP_SECRET}

